### ISSUE TITLE
ERROR: No matching distribution found for hibiapi

### ISSUE THREAD

**Issue by Orisland** [mixmoe/HibiAPI#112]
`pip install hibiapi`
![image](https://user-images.githubusercontent.com/59354152/127645800-50c10f60-36f7-4ebf-a766-9bbfd0fdcc5e.png)
如图。

**Comment by mnixry** [comment]
Python版本是应高于3.8

**Comment by Orisland** [comment]
> Python版本应`>=3.8`

还有救吗……
`python-multipart `安装了半天都是0.0.4
`ERROR: Cannot install hibiapi==0.6.0, hibiapi==0.7.0, hibiapi==0.7.1 and hibiapi==0.7.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    hibiapi 0.7.2 depends on python-multipart<0.0.6 and >=0.0.5
    hibiapi 0.7.1 depends on python-multipart<0.0.6 and >=0.0.5
    hibiapi 0.7.0 depends on python-multipart<0.0.6 and >=0.0.5
    hibiapi 0.6.0 depends on python-multipart<0.0.6 and >=0.0.5

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies `

**Comment by mnixry** [comment]
是CentOS7吗……~~如果是建议尽早换掉，推荐Ubuntu 20.04~~
这个看起来是Python编译安装[缺乏了必要的依赖库](https://stackoverflow.com/questions/27022373)~~Python编译安装坑巨多~~

**Comment by Orisland** [comment]
> 是CentOS7吗……~如果是建议尽早换掉，推荐Ubuntu 20.04~
> 这个看起来是Python编译安装[缺乏了必要的依赖库](https://stackoverflow.com/questions/27022373)~Python编译安装坑巨多~

阿里云服务器，系统为阿里优化后的系统，是centos7还是8还是红帽暂时不太清楚，但是看着像centos7，不确定。

**Comment by mnixry** [comment]
CentOS8的话应该可以直接`yum install python38 python38-pip`

> Heroku进入休眠的周期太短了，还不知道除了手动登陆唤醒外有什么办法

我是用[UptimeRobot](https://uptimerobot.com)定时检测服务器在线状态, 不过Heroku限制在线450小时一个月, 不好整

我建议用repl.it部署, 除了更新版本需要手动之外好像还是没什么限制的

**Comment by Orisland** [comment]
> CentOS8的话应该可以直接`yum install python38 python38-pip`
> 
> > Heroku进入休眠的周期太短了，还不知道除了手动登陆唤醒外有什么办法
> 
> 我是用[UptimeRobot](https://uptimerobot.com)定时检测服务器在线状态, 不过Heroku限制在线450小时一个月, 不好整
> 
> 我建议用repl.it部署, 除了更新版本需要手动之外好像还是没什么限制的

> yum install python38 python38-pip
Last metadata expiration check: 1:20:03 ago on Sat 31 Jul 2021 09:02:18 AM CST.
No match for argument: python38
No match for argument: python38-pip
Error: Unable to find a match: python38 python38-pip

不太行……
repl.it又是啥啊，佬怎么知道这么多可以免费部署的网站……

**Comment by mnixry** [comment]
> ```
> yum install python38 python38-pip
> Last metadata expiration check: 1:20:03 ago on Sat 31 Jul 2021 09:02:18 AM CST.
> No match for argument: python38
> No match for argument: python38-pip
> Error: Unable to find a match: python38 python38-pip
> ```

刚搜了一下，CentOS 8的仓库里面[应该是有`python38`的](https://centos.pkgs.org/8/centos-appstream-x86_64/python38-3.8.6-3.module_el8.4.0+665+abc3a503.x86_64.rpm.html)

> 试了一下好像不太行，repl公开链接依然需要氪……唉，能嫖的越来越少了。

刚刚试了一下，可以用，应该是姿势不对
要在配置文件里面改监听地址为`0.0.0.0`, 公开链接就自己出来了

![](https://user-images.githubusercontent.com/32300164/127739459-82223f92-b2f4-46ee-8764-34c8ca389d7b.png)

P.S: repl.it 依旧需要UptimeRobot保活

**Comment by Orisland** [comment]
> > ```
> > yum install python38 python38-pip
> > Last metadata expiration check: 1:20:03 ago on Sat 31 Jul 2021 09:02:18 AM CST.
> > No match for argument: python38
> > No match for argument: python38-pip
> > Error: Unable to find a match: python38 python38-pip
> > ```
> 
> 
> 刚搜了一下，CentOS 8的仓库里面[应该是有`python38`的](https://centos.pkgs.org/8/centos-appstream-x86_64/python38-3.8.6-3.module_el8.4.0+665+abc3a503.x86_64.rpm.html)
> 
> 
> > 试了一下好像不太行，repl公开链接依然需要氪……唉，能嫖的越来越少了。
> 
> 
> 刚刚试了一下，可以用，应该是姿势不对
> 
> 要在配置文件里面改监听地址为`0.0.0.0`, 公开链接就自己出来了
> 
> 
> ![](https://user-images.githubusercontent.com/32300164/127739459-82223f92-b2f4-46ee-8764-34c8ca389d7b.png)
> 
> 
> P.S: repl.it 依旧需要UptimeRobot保活

gotcha，我试试。

**Comment by Orisland** [comment]
> > ```
> > yum install python38 python38-pip
> > Last metadata expiration check: 1:20:03 ago on Sat 31 Jul 2021 09:02:18 AM CST.
> > No match for argument: python38
> > No match for argument: python38-pip
> > Error: Unable to find a match: python38 python38-pip
> > ```
> 
> 刚搜了一下，CentOS 8的仓库里面[应该是有`python38`的](https://centos.pkgs.org/8/centos-appstream-x86_64/python38-3.8.6-3.module_el8.4.0+665+abc3a503.x86_64.rpm.html)
> 
> > 试了一下好像不太行，repl公开链接依然需要氪……唉，能嫖的越来越少了。
> 
> 刚刚试了一下，可以用，应该是姿势不对
> 要在配置文件里面改监听地址为`0.0.0.0`, 公开链接就自己出来了
> 
> ![](https://user-images.githubusercontent.com/32300164/127739459-82223f92-b2f4-46ee-8764-34c8ca389d7b.png)
> 
> P.S: repl.it 依旧需要UptimeRobot保活

佬是不是指这样来访问？
![image](https://user-images.githubusercontent.com/59354152/127755635-f5224082-08f2-4755-8103-866fafcbde35.png)
然后用bot每隔一段时间保活？
请问佬设置唤醒周期应该为多久呢？
![image](https://user-images.githubusercontent.com/59354152/127755657-f335826d-0ba3-454c-a50a-02ffae40b2d7.png)
![IMG_6025](https://user-images.githubusercontent.com/59354152/127755675-13935562-6af1-427f-953a-6bebd93dd07c.PNG)

**Comment by mnixry** [comment]
> 这两个似乎都可以，但是下面的那个好像稍微慢一点。

从理论上你要分发链接应该用后者，你也可以按照官方文档自己解析一个域名上去

> 请问佬设置唤醒周期应该为多久呢？

默认给的五分钟应该够了

**Comment by Orisland** [comment]
> > 这两个似乎都可以，但是下面的那个好像稍微慢一点。
> 
> 从理论上你要分发链接应该用后者，你也可以按照官方文档自己解析一个域名上去
> 
> > 请问佬设置唤醒周期应该为多久呢？
> 
> 默认给的五分钟应该够了

get，感谢佬，api帮大忙了！
