### ISSUE TITLE
API for bcy.net

### ISSUE THREAD

**Issue by Ruriko** [mixmoe/HibiAPI#173]
Is it possible if you can make API for bcy.net?

**Comment by mnixry** [comment]
> Is it possible if you can make API for bcy.net?

Thank you for your suggestions. Can your provide any open source projects for reference?

Unfortunately, I possibly don't have enough time to deal with this feature. 
Anyway, Contributions is always welcomed, If you have any further idea, please feel free to reply, so please leave this issue open.

**Comment by Ruriko** [comment]
> > Is it possible if you can make API for bcy.net?
> 
> Thank you for your suggestions. Can you provide any open source projects for reference?
> 
> Unfortunately, I possibly don't have enough time to deal with this feature. Anyway, Contributions are always welcomed, If you have any further idea, please feel free to reply, so please leave this issue open.

Can't really provide any open source project since I planned to use a CMS like Wordpress, Drupal, Joomla. I think you can use https://github.com/journey-ad/pixiv-viewer as reference. All it need is to swap the api and edit the url structure since pixiv & bcy are similar sites

**Comment by Pretty9** [comment]
Perhaps these endpoints can provide some information:

Rank endpoints:
 - https://bcy.net/apiv3/rank/list/itemInfo?p=2&ttype=novel&sub_type=lastday&date=20211123
 - https://bcy.net/apiv3/rank/list/itemInfo?p=2&ttype=illust&sub_type=week&date=20211121
 - https://bcy.net/apiv3/rank/list/itemInfo?p=3&ttype=cos&sub_type=newPeople&date=20211123

Feed / Recommend endpoints:
- https://bcy.net/apiv3/common/getFeeds?refer=feed&direction=loadmore
- https://bcy.net/apiv3/common/getFeeds?refer=channel&direction=loadmore&cid=6618800650505421059
- https://bcy.net/apiv3/common/getFeeds?refer=channel&direction=loadmore&cid=6618800694038102275
- https://bcy.net/apiv3/common/getFeeds?refer=channel&direction=loadmore&cid=6618800677680316675

Search endpoint:
- https://bcy.net/apiv3/search/getContent?query=a%20cute%20cat&from=1&size=12&searchId=4bdbe019-3dc5-43ec-9a87-0495e8173c5c

But for Search endpoint, the result returned is a mix of illust, novel, cos, and Q&A, and the filter switch is not found.

**Comment by Ruriko** [comment]
@Pretty9 do you need the endpoints for user profile?

**Comment by Pretty9** [comment]
> @Pretty9 do you know the endpoints for user profile?

This endpoint contains the user's posts：
- https://bcy.net/apiv3/user/selfPosts?uid=1091195447018196&since=0

**Comment by Ruriko** [comment]
bcy.net have shut down
