### ISSUE TITLE
部署到 repl.it 时默认会重定向到 http 协议

### ISSUE THREAD

**Issue by journey-ad** [mixmoe/HibiAPI#21]
可以通过指定 uvicorn 运行参数`forwarded_allow_ips='*'`，或者指定环境变量`FORWARDED_ALLOW_IPS="*"`解决

后面编写 wiki 时可以注意下这点

配置说明 https://www.uvicorn.org/settings/#http

参考 https://stackoverflow.com/questions/63511413/fastapi-redirection-for-trailing-slash-returns-non-ssl-link

**Comment by mnixry** [comment]
感谢提醒, 我尝试在配置文件中也添加了该选项, 希望能解决问题(
