### ISSUE TITLE
接口请求：SauceNAO 搜图接口

### ISSUE THREAD

**Issue by journey-ad** [mixmoe/HibiAPI#22]
需注册账号获取 token
官方提供的接口在 web 端直接调用会有跨域问题

文档：https://saucenao.com/user.php?page=search-api

建议图片支持表单上传文件和从 url 获取

**Comment by mnixry** [comment]
大概做出来了
本来是想优化一下bitmask的api的, 结果这个bitmask怎么用根本没看懂 :rofl:
