### ISSUE TITLE
Current configuration will not reload as not all conditions are met,please refer to documentation

### ISSUE THREAD

**Issue by Ruriko** [mixmoe/HibiAPI#277]
I received a warning that says: ` WARNING  [2022/04/16 12:50:51.626 config:uvicorn.config:298] Current configuration will not reload as not all conditions are met,please refer to documentation.`
Which documentation is this referring to? what do I need to meet all the conditions?

**Comment by mnixry** [comment]
I have never encountered this problem. Are you using debug mode of HibiAPI under Windows? If so, this issue may be caused by limitation of operating system.

**Comment by Ruriko** [comment]
No I have it installed in Ubuntu 20.04 and debug mode is disable

**Comment by mnixry** [comment]
I have already located where the problem is. This warning will not affect normal production use. 

I will fix it soon, so please leave this issue open.
