### ISSUE TITLE
Debug 模式下 uvicorn 无限重载

### ISSUE THREAD

**Issue by StarHeartHunt** [mixmoe/HibiAPI#29]
在 `Debug` 模式下，`uvicorn` 的冷重载模式被启用。日志持续写入磁盘，uvicorn检测到变更后自动重载，uvicorn自动重载时又写入日志，导致重载无限循环。

搜了一下没搜到能排除文件的解决方案，倒是有[设置监控目录](https://stackoverflow.com/questions/64118680/reload-flag-with-uvicorn-can-we-exclude-certain-code)的解决方案

**Comment by mnixry** [comment]
这个问题在我这里无法被复现欸

**Comment by mnixry** [comment]
我先close了, 如果之后再次遇到类似问题可以随时reopen (

**Comment by mnixry** [comment]
已经确认, 该问题为上游依赖`uvicorn[standard]`所依赖的`watchgod`库问题
经过尝试, 该问题无法在本程序的范围内进行修复, 目前请在使用该项目的时候尽量使用虚拟环境来进行操作
