### ISSUE TITLE
部署完成后在前端无法调用

### ISSUE THREAD

**Issue by wukibaka** [mixmoe/HibiAPI#296]
大佬 我用你的这个项目搭建好了pixiv的api 但我把api地址丢到pixiv-viewer项目里 用vercel部署pixiv-viewer不可用 但api请求到的东西是正确的

**Comment by wukibaka** [comment]
不知道怎么给log（

**Comment by mnixry** [comment]
我觉得应该是CORS的问题，你配一下CORS试试

**Comment by wukibaka** [comment]
> 我觉得应该是CORS的问题，你配一下CORS试试

cors是啥 怎么配（

**Comment by mnixry** [comment]
> cors是啥 怎么配（

https://github.com/mixmoe/HibiAPI/blob/816803a8d57cc0b040bce66ea2dc482ebd62f58d/hibiapi/configs/general.yml#L25-L33

**Comment by wukibaka** [comment]
> > cors是啥 怎么配（
> 
> 配置文件里面
> 
> https://github.com/mixmoe/HibiAPI/blob/816803a8d57cc0b040bce66ea2dc482ebd62f58d/hibiapi/configs/general.yml#L25-L33

是直接在origins下面加部署的pixiv-viewer的地址吗

**Comment by mnixry** [comment]
> 是直接在origins下面加部署的pixiv-viewer的地址吗

是 

> 有没有关掉cors的方法

有，写`*`就行，请参考[MDN文档](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS)

**Comment by wukibaka** [comment]
> > 是直接在origins下面加部署的pixiv-viewer的地址吗
> 
> 是 
> 
> > 有没有关掉cors的方法
> 
> 有，写`*`就行，请参考[MDN文档](https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS)

感谢大佬 刚刚也想到了 部署完后能用了

**Comment by wukibaka** [comment]
大大 怎么用环境变量的方式配置cors呢

**Comment by wukibaka** [comment]
general_server_cros_origins=*
这样吗

**Comment by mnixry** [comment]
> 大大 怎么用环境变量的方式配置cors呢

https://github.com/mixmoe/HibiAPI/blob/2a569e6b4188484685c425c3e5a1af4b0792720f/app.json#L26-L28

`GENERAL_SERVER_CORS_ORIGINS=["*"]`

**Comment by wukibaka** [comment]
> > 大大 怎么用环境变量的方式配置cors呢
> 
> https://github.com/mixmoe/HibiAPI/blob/2a569e6b4188484685c425c3e5a1af4b0792720f/app.json#L26-L28
> 
> `GENERAL_SERVER_CORS_ORIGINS=["*"]`
> 

好的 谢谢大佬
