### ISSUE TITLE
api返回301状态码

### ISSUE THREAD

**Issue by 20020314** [mixmoe/HibiAPI#301]
大佬我用反向代理开启ssl后后api实际请求地址为http并没有走ssl，导致api状态码为301，并无数据返回

**Comment by mnixry** [comment]
抱歉，没有听明白你是什么意思……

**Comment by 20020314** [comment]
`INFO     [2022/05/31 02:29:16.204 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32872 | GET | 'http://api.linmi.fun/docs' | 0.891ms | Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1 | 200
 INFO     [2022/05/31 02:29:17.049 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32872 | GET | 'http://api.linmi.fun/' | 0.614ms | Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0 | 302
 INFO     [2022/05/31 02:29:17.369 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32872 | GET | 'http://api.linmi.fun/openapi.json' | 210.802ms | Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Mobile/15E148 Safari/604.1 | 200
 INFO     [2022/05/31 02:29:17.370 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32874 | GET | 'http://api.linmi.fun/docs' | 0.707ms | Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0 | 200
 INFO     [2022/05/31 02:29:17.953 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32874 | GET | 'http://api.linmi.fun/favicon.ico' | 0.884ms | Mozilla/4.054101423 Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1) | 404
 INFO     [2022/05/31 02:29:23.602 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32876 | GET | 'http://api.linmi.fun/' | 0.610ms | Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Mobile Safari/537.36 | 302
 INFO     [2022/05/31 02:29:23.746 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32876 | GET | 'http://api.linmi.fun/docs' | 1.089ms | Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Mobile Safari/537.36 | 200
 INFO     [2022/05/31 02:30:06.244 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32878 | GET | 'http://api.linmi.fun/' | 0.615ms | Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0 | 302
 INFO     [2022/05/31 02:30:06.505 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32878 | GET | 'http://api.linmi.fun/docs' | 0.551ms | Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0 | 200
 INFO     [2022/05/31 02:31:11.072 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32920 | GET | 'http://api.linmi.fun/pixiv/?type=rank&mode=week&page=1&date=2022-05-29' | 0.798ms | Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1 com.hydx.browserone167 | 301
 INFO     [2022/05/31 02:31:11.075 middlewares:hibiapi.app.middlewares:61] 10.0.1.3:32920 | GET | 'http://api.linmi.fun/pixiv/?type=rank&mode=day&page=1&date=2022-05-29' | 0.814ms | Mozilla/5.0 (iPhone; CPU iPhone OS 15_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1 com.hydx.browserone167 | 301 `
为什么get报310

**Comment by 20020314** [comment]
反向代理后开启了ssl，请求https地址日志显示请求的http地址

**Comment by mnixry** [comment]
> 为什么get报310

这是预期行为，请求地址不是这个。这个301是重定向请求，为了给旧版HibiAPI做兼容的。
现在的请求地址请在部署完成后访问查看生成的文档获得

> 反向代理后开启了ssl，请求https地址日志显示请求的http地址

需要设置一个环境变量，参考 #21

**Comment by 20020314** [comment]
好的感谢大佬

**Comment by mnixry** [comment]
鉴于该Issue提出的问题看起来已经解决且长期没有活动, 我将关闭此issue

如果您有任何疑问, 欢迎随时reopen或者提交一个新的issue
