### ISSUE TITLE
Url image 403 Forbidden 

### ISSUE THREAD

**Issue by Sansekai** [mixmoe/HibiAPI#325]
all image url result 403 Forbidden 

https://api.obfs.dev/api/pixiv/illust?id=100064247

**Comment by mnixry** [comment]
HibiAPI returns the Pixiv upstream response "as is", so it returns the Pixiv image link directly.

To access the image stored in `i.pximg.net` directly, you need to add the HTTP header `Referer: https://www.pixiv.net` to bypass the origin check. Or you can replace `i.pximg.net` with `pximg.obfs.dev`, the latter is my self-hosted reverse proxy which supports directly access from any origin.

**Comment by Sansekai** [comment]
> 

Ah.. i see

Thanks
