### ISSUE TITLE
[bug] `/api/pixiv/rank` 返回的列表数据可能会有缺失

### ISSUE THREAD

**Issue by asadahimeka** [mixmoe/HibiAPI#378]
如图，`/api/pixiv/rank` 的这个 `size` 参数好像不能设置返回列表的条数，源站返回的一直是 30 条，然后由于 `size` 默认是 50 ，导致 `size`  不为 30 时从第 2 页开始返回的数据缺失。想了半天不知道怎么解决，只能传参时传 30 或者暂时把默认条数改为 30。
可能所有有 `offset` 参数的 API 都会有这个问题。
![image](https://user-images.githubusercontent.com/31837214/215103288-8b6005c0-9fc2-4edf-8f03-25a8bd7f217c.png)
<img src="https://user-images.githubusercontent.com/31837214/215102919-49f1a6e4-c7b9-478f-b871-186f7d422140.png" >
<img src="https://user-images.githubusercontent.com/31837214/215102818-3ccd94e7-fdbf-4c3e-b00e-5506d106da13.png" >
<img src="https://user-images.githubusercontent.com/31837214/215103013-3c4d9a6f-99cb-4874-961a-7faf5b4295ef.png" >

**Comment by mnixry** [comment]
这个Size参数没记错应该是为了做兼容Imjad API（老黄历了），可能没法改

~~你就先把这个改到30吧，然后看看别的有没有不一样的改掉~~

**Comment by asadahimeka** [comment]
OK 我自己改成 30 用着了先

**Comment by mnixry** [comment]
有空可以给个PR（

~~然后我在想要不要干脆把这个size参数删了，反正也不太管用~~

**Comment by asadahimeka** [comment]
PR 提了

然后问题主要是现在 P 站返回的是 30 条，以后也说不好是返回几条，分页有些古怪 <img height=25 src="https://user-images.githubusercontent.com/31837214/214237746-f3a5420f-9f2e-4eff-b5a4-ce2cb483a6c2.png" >，

或者是解析它返回的 `next_url` 再给到 API 参数 `offset`，但这样就与之前不兼容了。

还是就先这样吧（
