### ISSUE TITLE
哔咔advanced_search的page问题

### ISSUE THREAD

**Issue by yeyang52** [mixmoe/HibiAPI#381]
我在使用哔咔的搜索接口的时候发现使用page参数无法生效，后获取官方接口发现page并不是以body传输而是以参数的形式传输
![image](https://user-images.githubusercontent.com/107110851/215353229-83c3e0c5-2a80-47c8-8abf-167401b1e23b.png)

**Comment by mnixry** [comment]
离谱，我稍后修复（或者你给个PR？）

**Comment by yeyang52** [comment]
抱歉，我并不熟悉py的语法，以免出现更多bug🤕
