### ISSUE TITLE
希望添加pixiv搜索tag

### ISSUE THREAD

**Issue by yeyang52** [mixmoe/HibiAPI#382]
我在使用pixiv搜索的时候发现搜索tag的翻译时并不好使，所以希望可以添加搜索tag的接口
我抓取的接口是`v2/search/autocomplete?word=tag`

**Comment by asadahimeka** [comment]
`v2/search/autocomplete` 可以自动补全 tag
要使用 tag 的翻译名称搜索作品的话可以往 `v1/search/illust` 传入 `include_translated_tag_results=true`
这个接口我在自己的 [实例](https://hibi2.cocomi.cf/docs#tag/Pixiv/operation/search_autocomplete_api_pixiv_search_autocomplete_get) 里加上了 可以测试看看
没问题的话 我可以提个 PR (

**Comment by yeyang52** [comment]
> `v2/search/autocomplete`可以自动补全 tag 要使用 tag 的翻译名称搜索作品的话可以往 传入 这个接口我在自己的 [实例](https://hibi2.cocomi.cf/docs#tag/Pixiv/operation/search_autocomplete_api_pixiv_search_autocomplete_get) 里加上了 可以测试看看 没问题的话 我可以提个 PR （`v1/search/illust``include_translated_tag_results=true`
感谢我加上这个参数后成功了

**Comment by mnixry** [comment]
> 可以测试看看 没问题的话 我可以提个 PR (

👀

**Comment by yeyang52** [comment]
> > 可以测试看看 没问题的话 我可以提个 PR (
> 
> 👀

我已经进行pr请检查一下代码

**Comment by asadahimeka** [comment]
你们加上了 那我就不加了 
注意休息啊 <img height=25 src="https://user-images.githubusercontent.com/31837214/214237746-f3a5420f-9f2e-4eff-b5a4-ce2cb483a6c2.png" >
