### ISSUE TITLE
Directly usage of command run is deprecated, please use run run instead.

### ISSUE THREAD

**Issue by Lo-kin** [mixmoe/HibiAPI#386]
WARNING  [2023/02/03 11:45:48.168 __main__:hibiapi.__main__:61] Directly usage of command run is deprecated, please use run run instead.
使用 python -m hibiapi run 时产生的信息 ， 是命令行有误吗

在指定workers大于1的时候，会产生socket错误，并且使用ctrl+c无法正常退出

**Comment by mnixry** [comment]
这个提示确实是代码Bug

后面那个 workers > 1 出错这个在我这边平台上无法复现, 你能提供更多信息吗?
