### ISSUE TITLE
似乎有一处代码会引起递归错误

### ISSUE THREAD

**Issue by journey-ad** [mixmoe/HibiAPI#4]
https://github.com/mixmoe/HibiAPI/blob/04b222e7692a648974b0569bc44a1753340d6dd2/utils/utils.py#L93-L96

95行获取`self.type_checking`时会再次触发`__getattribute__`产生无限递归

我把95行的判断条件改为`name == 'type_checking' and not obj`后不再报错，但我不熟悉Python开发，不确定这样写是否正确或者有更好的写法

**Comment by mnixry** [comment]
感谢指出, 已经在 https://github.com/mixmoe/HibiAPI/commit/f7fc667fc7f12d6c48144993e5ac27769c6618d9 中修复
写的时候没注意这一点(
