### ISSUE TITLE
pixiv 无法获取图片

### ISSUE THREAD

**Issue by Jerry-Z07** [mixmoe/HibiAPI#403]
我使用了正确的配置自建了hibiapi服务，但我无法请求pixiv上的图片（已配置代理正常访问pixiv）
报错如图
![4430c29e145d7bc3ec22d70ba1970cc9](https://github.com/user-attachments/assets/90fca29a-66fd-4a34-9dcb-726ea881ac67)

**Comment by mnixry** [comment]
URL 拼接的不对
![图片](https://github.com/user-attachments/assets/31dbca4b-a9a8-433c-9dc5-b6018d538e61)

**Comment by 20080217** [comment]
你看你请求的url，多打了一个斜杠 //api

**Comment by Jerry-Z07** [comment]
问题已解决，谢谢

**Comment by l3nt7ibr** [comment]
看笨蛋.jpg
