### ISSUE TITLE
访问哔咔漫画图片提示没有权限

### ISSUE THREAD

**Issue by bilili-syy** [mixmoe/HibiAPI#404]
将API返回的fileServer和path进行拼接之后访问图片提示没有权限.请问是我的方法错了吗还是要在哪里获取token

**Comment by mnixry** [comment]
看了下他们网页版的实现, 应该是 `"https://s3.picacomic.com/static/" + path`, `fileServer + '/static/' + path` 也行

**Comment by bilili-syy** [comment]
> 看了下他们网页版的实现, 应该是 `"https://s3.picacomic.com/static/" + path`, `fileServer + '/static/' + path` 也行 

感谢您~已经成功
