### ISSUE TITLE
请求 pixiv 相关接口全部返回 422

### ISSUE THREAD

**Issue by Chendihe4975** [mixmoe/HibiAPI#54]
请求 pixiv 相关接口全部返回 422

代码如下 : 
```python
import requests
r = requests.get('https://api.dihe.moe/pixiv/?illust=89395577')
print(r.json())
```

返回 :

```json
{
    "url": "https://api.dihe.moe/pixiv/?illust=89395577",
    "time": "2021-04-25T17:15:53.244304",
    "code": 422,
    "detail": "1 validation error for Illust\nid\n  field required (type=value_error.missing)",
    "trace": null,
    "headers": {},
    "validation": [
        {
            "loc": [
                "id"
            ],
            "msg": "field required",
            "type": "value_error.missing"
        }
    ]
}
```
确定pixiv refresh_token 有效的情况下, 也尝试请求文档提供接口 <https://api.obfs.dev/api/pixiv/> , 仍然返回 422 。

**Comment by dynxer** [comment]
应该为 `/api/pixiv/illust?id=89395577`
Refer: [Pixiv - illust](https://api.obfs.dev/docs#operation/illust_api_pixiv_illust_get)

**Comment by Chendihe4975** [comment]
> 应该为`/api/pixiv/illust?id=89395577`
> Refer：[Pixiv-illust](https://api.obfs.dev/docs#operation/illust_api_pixiv_illust_get)

草，我悟了，感谢

**Comment by mnixry** [comment]
https://api.obfs.dev/docs 这个地方有API文档
或者搭建以后直接访问监听地址也有文档，可以提供参考
（但是文档还没写完）
