### ISSUE TITLE
Cannot uninstall 'PyYAML'

### ISSUE THREAD

**Issue by Ruriko** [mixmoe/HibiAPI#81]
I run this command `pip install -r requirements.txt` but get error:
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
I'm running on Ubuntu 20.04 & Python 3.8

**Comment by mnixry** [comment]
> ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

According to this error message, it shows it conflict with system pre-installed package.
In this condition, we suggest you [**use virtual environment**](https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/26/python-virtual-env/) to isolate dependencies between different projects.
