### ISSUE TITLE
外网无法访问

### ISSUE THREAD

**Issue by shirokurakana** [mixmoe/HibiAPI#9]
尝试在winserver2012R2上运行，有公网ip，端口已放行，通过127.0.0.1可正常使用，但外网访问提示访问被拒绝，内网（192.168.x.x）地址访问也被拒绝。

**Comment by journey-ad** [comment]
`configs/general.yml`中的`host`改为`0.0.0.0`

**Comment by shirokurakana** [comment]
懂了（捂脸）
