### ISSUE TITLE
網易雲音樂 playlist 返回數據不正確

### ISSUE THREAD

**Issue by lekoOwO** [mixmoe/HibiAPI#94]
https://api.obfs.dev/api/netease/playlist?id=754582478 內應該有數首歌

卻只返回第一首

**Comment by mnixry** [comment]
还真有这个问题...好像是网易云网页版请求的时候改了参数
今晚看一下

**Comment by mnixry** [comment]
https://github.com/mixmoe/HibiAPI/blob/5f45f48721b2f904a844a36c68c8e345b975c484/hibiapi/api/netease/api.py#L196
改成`v6`就好了:rofl:, 返回体看起来没有差别
等待CI部署到demo可能需要几分钟
